# This is a basic workflow to help you get started with Actions

name: test repos

# Controls when the workflow will run
on:

  workflow_dispatch:

    # Steps represent a sequence of tasks that will be executed as part of the job
jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Run a command and capture the output
        id: plan
        run: echo "Hello$World" # Example command, replace with your own

      - name: Replace special character in the output
        run: |
          original_output="${{ steps.plan.outputs.stdout }}"
          modified_output=$(echo "$original_output" | sed 's/\$/-/g')
          echo "::set-output name=modified_output::$modified_output"



